// ================================================================
// input_digit.h
// Hardcoded input image in fm_t (ap_fixed<16,6>) format.
// Included directly into lenet5_mnist.h so the HLS top-level
// has a default input available at synthesis and simulation time.
//
// TO CHANGE THE INPUT DIGIT:
//   1. Change DIGIT_LABEL to whichever digit you drew (0-9)
//   2. Edit INPUT_IMAGE rows — ON = white pixel, OFF = black
//   3. Re-run C Simulation / Synthesis — no other file changes needed
// ================================================================

#ifndef INPUT_DIGIT_H
#define INPUT_DIGIT_H

// ================================================================
// >>> CHANGE THIS to match the digit drawn below <<<
// ================================================================
#define DIGIT_LABEL  5

// ================================================================
// Pixel constants in fm_t = ap_fixed<16,6>
//   ON  = fm_t(1.0)  — white / ink pixel
//   OFF = fm_t(0.0)  — black / background pixel
// ================================================================
#define IMG_ON   fm_t(1.0f)
#define IMG_OFF  fm_t(0.0f)

// ================================================================
// INPUT_IMAGE[1][32][32]  — digit 5 (S-shape)
//
// ASCII diagram of what is drawn
// (rows 0-3 and 28-31 are zero-padding, cols 0-9 and 23-31 too):
//
//  row  4: ..........#############...
//  row  5: ..........#.............
//  ...
//  row 14: ..........#.............
//  row 15: ..........#############...
//  row 16: ......................#...
//  ...
//  row 26: ......................#...
//  row 27: ..........#############...
// ================================================================
static volatile fm_t INPUT_IMAGE[IN_CH][IN_H][IN_W] = {{
/* row  0 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row  1 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row  2 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row  3 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row  4 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_ON ,IMG_ON ,IMG_ON ,IMG_ON ,IMG_ON ,IMG_ON ,IMG_ON ,IMG_ON ,IMG_ON ,IMG_ON ,IMG_ON ,IMG_ON ,IMG_ON ,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row  5 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_ON ,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row  6 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_ON ,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row  7 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_ON ,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row  8 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_ON ,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row  9 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_ON ,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row 10 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_ON ,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row 11 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_ON ,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row 12 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_ON ,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row 13 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_ON ,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row 14 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_ON ,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row 15 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_ON ,IMG_ON ,IMG_ON ,IMG_ON ,IMG_ON ,IMG_ON ,IMG_ON ,IMG_ON ,IMG_ON ,IMG_ON ,IMG_ON ,IMG_ON ,IMG_ON ,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row 16 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_ON ,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row 17 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_ON ,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row 18 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_ON ,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row 19 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_ON ,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row 20 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_ON ,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row 21 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_ON ,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row 22 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_ON ,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row 23 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_ON ,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row 24 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_ON ,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row 25 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_ON ,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row 26 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_ON ,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row 27 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_ON ,IMG_ON ,IMG_ON ,IMG_ON ,IMG_ON ,IMG_ON ,IMG_ON ,IMG_ON ,IMG_ON ,IMG_ON ,IMG_ON ,IMG_ON ,IMG_ON ,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row 28 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row 29 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row 30 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
/* row 31 */{IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF,IMG_OFF},
}};

#endif // INPUT_DIGIT_H
